"""add rental_delay_months

Revision ID: 54f3c5c1bb6d
Revises: 719883dd7ef3
Create Date: 2026-03-30 09:18:48.890241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f3c5c1bb6d'
down_revision: Union[str, Sequence[str], None] = '719883dd7ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('str_assumptions', sa.Column('rental_delay_months', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('str_assumptions', sa.Column('local_gross_receipts_tax_pct', sa.Numeric(precision=6, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('str_assumptions', 'local_gross_receipts_tax_pct')
    op.drop_column('str_assumptions', 'rental_delay_months')
    # ### end Alembic commands ###
