DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

PROFILE_TEMPLATES: dict[str, list[dict] | None] = {
    "vt_ski_town": [
        {"month": 1, "nightly_rate": 350, "occupancy_pct": 75},
        {"month": 2, "nightly_rate": 350, "occupancy_pct": 80},
        {"month": 3, "nightly_rate": 300, "occupancy_pct": 60},
        {"month": 4, "nightly_rate": 150, "occupancy_pct": 25},
        {"month": 5, "nightly_rate": 175, "occupancy_pct": 35},
        {"month": 6, "nightly_rate": 250, "occupancy_pct": 60},
        {"month": 7, "nightly_rate": 275, "occupancy_pct": 70},
        {"month": 8, "nightly_rate": 275, "occupancy_pct": 70},
        {"month": 9, "nightly_rate": 275, "occupancy_pct": 65},
        {"month": 10, "nightly_rate": 300, "occupancy_pct": 75},
        {"month": 11, "nightly_rate": 200, "occupancy_pct": 35},
        {"month": 12, "nightly_rate": 325, "occupancy_pct": 70},
    ],
    "vt_lakefront": [
        {"month": 1, "nightly_rate": 175, "occupancy_pct": 25},
        {"month": 2, "nightly_rate": 175, "occupancy_pct": 30},
        {"month": 3, "nightly_rate": 150, "occupancy_pct": 20},
        {"month": 4, "nightly_rate": 150, "occupancy_pct": 20},
        {"month": 5, "nightly_rate": 250, "occupancy_pct": 50},
        {"month": 6, "nightly_rate": 350, "occupancy_pct": 80},
        {"month": 7, "nightly_rate": 400, "occupancy_pct": 90},
        {"month": 8, "nightly_rate": 400, "occupancy_pct": 90},
        {"month": 9, "nightly_rate": 300, "occupancy_pct": 65},
        {"month": 10, "nightly_rate": 275, "occupancy_pct": 55},
        {"month": 11, "nightly_rate": 175, "occupancy_pct": 25},
        {"month": 12, "nightly_rate": 175, "occupancy_pct": 25},
    ],
    "vt_general": [
        {"month": 1, "nightly_rate": 225, "occupancy_pct": 45},
        {"month": 2, "nightly_rate": 225, "occupancy_pct": 50},
        {"month": 3, "nightly_rate": 200, "occupancy_pct": 35},
        {"month": 4, "nightly_rate": 175, "occupancy_pct": 30},
        {"month": 5, "nightly_rate": 200, "occupancy_pct": 45},
        {"month": 6, "nightly_rate": 250, "occupancy_pct": 65},
        {"month": 7, "nightly_rate": 275, "occupancy_pct": 75},
        {"month": 8, "nightly_rate": 275, "occupancy_pct": 75},
        {"month": 9, "nightly_rate": 250, "occupancy_pct": 65},
        {"month": 10, "nightly_rate": 250, "occupancy_pct": 70},
        {"month": 11, "nightly_rate": 175, "occupancy_pct": 30},
        {"month": 12, "nightly_rate": 200, "occupancy_pct": 40},
    ],
    "flat": None,
}
